// Package export serialises env maps to various textual formats.
//
// Supported formats:
//
//	"dotenv"  – standard KEY=VALUE lines, optionally prefixed with "export"
//	"shell"   – alias for dotenv; intended for sourcing in shell scripts
//	"inline"  – all pairs on a single space-separated line
//
// Basic usage:
//
//	env := map[string]string{"FOO": "bar", "BAZ": "qux"}
//	if err := export.Write(os.Stdout, env, export.DefaultOptions()); err != nil {
//		log.Fatal(err)
//	}
//
// To emit shell-sourceable output with a header comment:
//
//	opts := export.DefaultOptions()
//	opts.Export  = true
//	opts.Comment = "generated by envdiff"
//	export.Write(os.Stdout, env, opts)
package export
