package export

import (
	"strings"
	"testing"
)

func TestWrite_DotenvDefaults(t *testing.T) {
	env := map[string]string{"FOO": "bar", "BAZ": "qux"}
	var sb strings.Builder
	if err := Write(&sb, env, DefaultOptions()); err != nil {
		t.Fatal(err)
	}
	out := sb.String()
	if !strings.Contains(out, "FOO=bar") {
		t.Errorf("expected FOO=bar in output, got: %s", out)
	}
	if !strings.Contains(out, "BAZ=qux") {
		t.Errorf("expected BAZ=qux in output, got: %s", out)
	}
}

func TestWrite_ExportPrefix(t *testing.T) {
	env := map[string]string{"KEY": "val"}
	var sb strings.Builder
	opts := DefaultOptions()
	opts.Export = true
	if err := Write(&sb, env, opts); err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(sb.String(), "export KEY=val") {
		t.Errorf("expected export prefix, got: %s", sb.String())
	}
}

func TestWrite_InlineFormat(t *testing.T) {
	env := map[string]string{"A": "1", "B": "2"}
	var sb strings.Builder
	opts := Options{Format: FormatInline, Sorted: true}
	if err := Write(&sb, env, opts); err != nil {
		t.Fatal(err)
	}
	got := strings.TrimSpace(sb.String())
	if got != "A=1 B=2" {
		t.Errorf("unexpected inline output: %q", got)
	}
}

func TestWrite_QuotesSpaces(t *testing.T) {
	env := map[string]string{"MSG": "hello world"}
	var sb strings.Builder
	if err := Write(&sb, env, DefaultOptions()); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(sb.String(), `MSG="hello world"`) {
		t.Errorf("expected quoted value, got: %s", sb.String())
	}
}

func TestWrite_Comment(t *testing.T) {
	env := map[string]string{"X": "y"}
	var sb strings.Builder
	opts := DefaultOptions()
	opts.Comment = "generated by envdiff"
	if err := Write(&sb, env, opts); err != nil {
		t.Fatal(err)
	}
	lines := strings.Split(sb.String(), "\n")
	if lines[0] != "# generated by envdiff" {
		t.Errorf("expected comment header, got: %q", lines[0])
	}
}

func TestWrite_UnknownFormat(t *testing.T) {
	env := map[string]string{"K": "v"}
	var sb strings.Builder
	err := Write(&sb, env, Options{Format: "xml"})
	if err == nil {
		t.Fatal("expected error for unknown format")
	}
}
